spring.application.name=Todo

logging.level.org.springdoc=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.boot.autoconfigure=DEBUG

# JWT Configuration
jwt.secret=mySecretKeyWhichIsVeryLongAndSecureAtLeast256Bits
jwt.expiration=900000

# H2
spring.datasource.url=jdbc:h2:mem:tododb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Mostrar SQL no console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Para aceitar tanto o nome do enum quanto o displayName
spring.jackson.deserialization.READ_ENUMS_USING_TO_STRING=true

# SpringDoc OpenAPI Configuration
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.operationsSorter=alpha
springdoc.swagger-ui.display-request-duration=true
springdoc.swagger-ui.filter=true

# Para desenvolvimento com H2
springdoc.show-actuator=true